### ISSUE TITLE
Convert cloud event into a JS Object

### ISSUE THREAD

**Issue by lance** [openshift-cloud-functions/faas-js-runtime-image#11]
The `CloudEvent` data that is unmarshalled and attached to the `Context` instance before calling the hosted function is really only accessible via the `CloudEvent.toString()` function, which returns a string that looks like this:

```json
 {"specversion":"0.2","id":"32904c7b-1988-4f15-b124-7de161ea4029","type":"dev.knative.cronjob.event","source":"/apis/v1/namespaces/js-faas-demo/cronjobsources/testfunc-cronjob-source","time":"2019-09-17T21:06:00.000Z","contenttype":"application/json","knativehistory":"testfunc-channel-tn4h6.js-faas-demo.svc.cluster.local","data":{"message":"Example message to test Knative Eventing functionality."}}
```
Why don't we just do this when attaching it to the context?

```js
context.cloudevent = JSON.parse(cldevent.toString());
```
Since this is almost certainly what the function writer will do in the end.

**Comment by slinkydeveloper** [comment]
:+1:

**Comment by zroubalik** [comment]
And what about using `Object Cloudevent.format()` [as mentioned here in the API](https://github.com/cloudevents/sdk-javascript#cloudevent-class)

**Comment by lance** [comment]
@zroubalik yes that makes sense - not sure how I missed that!

**Comment by zroubalik** [comment]
@lance That was my original intention, but I forgot about it :roll_eyes:
